"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CommandType = void 0;
var CommandType;
(function (CommandType) {
    CommandType["GET_TRANSPORT_QUEST"] = "GET_TRANSPORT_QUEST";
    CommandType["COLONIZATION"] = "COLONIZATION";
    CommandType["EXTERMINATION"] = "EXTERMINATION";
    CommandType["INFO"] = "INFO";
    CommandType["DEPOSIT"] = "DEPOSIT";
    CommandType["DEPOSIT_CLOSE"] = "DEPOSIT_CLOSE";
    CommandType["CREDIT"] = "CREDIT";
    CommandType["CREDIT_REPAY"] = "CREDIT_REPAY";
    CommandType["EXCHANGE"] = "EXCHANGE";
    CommandType["EXCHANGE_CANCEL"] = "EXCHANGE_CANCEL";
    CommandType["GET_EMBRYO"] = "GET_EMBRYO";
    CommandType["GET_VIRUS"] = "GET_VIRUS";
    CommandType["CHANGE_JOB"] = "CHANGE_JOB";
    CommandType["LEVEL_UP"] = "LEVEL_UP";
    CommandType["EXP_LEARN"] = "EXP_LEARN";
    CommandType["EXP_BOOST"] = "EXP_BOOST";
    CommandType["EXP_BUY_DATABASE"] = "EXP_BUY_DATABASE";
    CommandType["ENSURANCE"] = "ENSURANCE";
    CommandType["CONTRACT_CREATE"] = "CONTRACT_CREATE";
    CommandType["CONTRACT_APPLY"] = "CONTRACT_APPLY";
})(CommandType || (exports.CommandType = CommandType = {}));
