export enum EffectType {
    DESTROY = 1,
    WARPIN = 2,
    WARPOUT = 3,
    LANDING = 4,
    ESCAPE = 5,
    DAMAGE = 6,
    ATTACK = 7,
    STANDBY = 8,
    START = 9,
    MOVE = 10,
    STOP = 11,
    OPEN = 12,
    WORK = 13,
    CLOSE = 14,
    TRANSFORM = 15,
    SKILLS = 100,
    ABILITIES = 101,
    INDICATORS = 102,
    SKILL_BLAST = 626,
    SKILL_BLIND = 627
}
