export declare enum CommandType {
    COLONIZATION = "COLONIZATION",
    EXTERMINATION = "EXTERMINATION",
    INFO = "INFO",
    DEPOSIT = "DEPOSIT",
    DEPOSIT_CLOSE = "DEPOSIT_CLOSE",
    CREDIT = "CREDIT",
    CREDIT_REPAY = "CREDIT_REPAY",
    EXCHANGE = "EXCHANGE",
    EXCHANGE_CANCEL = "EXCHANGE_CANCEL",
    GET_EMBRYO = "GET_EMBRYO",
    GET_VIRUS = "GET_VIRUS",
    CHANGE_HULL = "CHANGE_HULL"
}
