"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Slot = void 0;
var Slot;
(function (Slot) {
    Slot["HULL"] = "HULL";
    Slot["ENGINE"] = "ENGINE";
    Slot["TANK"] = "TANK";
    Slot["RADAR"] = "RADAR";
    Slot["SCANNER"] = "SCANNER";
    Slot["DROID"] = "DROID";
    Slot["GRIPPER"] = "GRIPPER";
    Slot["PROTECTOR"] = "PROTECTOR";
    Slot["WEAPON1"] = "WEAPON1";
    Slot["WEAPON2"] = "WEAPON2";
    Slot["WEAPON3"] = "WEAPON3";
    Slot["WEAPON4"] = "WEAPON4";
    Slot["WEAPON5"] = "WEAPON5";
    Slot["ARTIFACT1"] = "ARTIFACT1";
    Slot["ARTIFACT2"] = "ARTIFACT2";
    Slot["ARTIFACT3"] = "ARTIFACT3";
    Slot["ARTIFACT4"] = "ARTIFACT4";
})(Slot = exports.Slot || (exports.Slot = {}));
